sudo: false

language: ruby

rvm:
  - 2.4.4

cache: bundler

script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash deploy.sh --source-only; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash deploy.sh; fi'
